datasets:
  syn_coco_vqa:
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
              - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/vqav2/synthetic_captions_1000.json # vqa_train.json
          storage:
              - /leonardo_work/EUHPC_D25_055/jli/dataset/syn_coco/synthetic_captions_1000.json
        val:
          url:
              - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/vqav2/synthetic_captions_1000.json # vqa_val_eval.json
          storage:
              - /leonardo_work/EUHPC_D25_055/jli/dataset/syn_coco/synthetic_captions_1000.json
        test:
          url:
              - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/vqav2/synthetic_captions_1000.json # vqa_test.json
          storage:
              - /leonardo_work/EUHPC_D25_055/jli/dataset/syn_coco/synthetic_captions_1000.json
      images:
          storage: /leonardo_work/EUHPC_D25_055/jli/dataset/train2017/
